version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATABASE_USER=postgres
      - DATABASE_HOST=db
      - DATABASE_NAME=todo_db
      - DATABASE_PASSWORD=postgres
      - DATABASE_PORT=5432
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Initialize database with your queries.sql
      - ./queries.sql:/docker-entrypoint-initdb.d/queries.sql
    restart: unless-stopped

volumes:
  postgres_data:
